### ISSUE TITLE
Cannot use Client::connect in a background task

### ISSUE THREAD

**Issue by alexanderjanke** [adnanademovic/simetry#2]
Hi,

I cannot seem to use Client::connect in a background tokio task:

```rust
#[tokio::main]
async fn main() {
  tokio::spawn(async move {
    let mut client = Client::connect(Duration::from_secs(1)).await;
    // do some iRacing stuff
  });

  // do something else
}
```

The error is: `future is not Send as this value is used across an await`, caused by `src\iracing\client.rs:267``:

![image](https://github.com/adnanademovic/simetry/assets/33967771/972d8c99-4cb8-447b-b309-328cb2b9a73c)

**Comment by adnanademovic** [comment]
Since the Windows API doesn't give us `Send` safety for shared memory handles, I'm not forcing the trait either.

As a result the iRacing client has to live on a single thread (unless someone wants to do the work of guaranteeing that handles can be sendable)

**Comment by adnanademovic** [comment]
Well that's annoying.

I won't have a chance in the next few days to investigate, but once I do I'll try to get things to implement Send/Sync where possible.

**Comment by adnanademovic** [comment]
I've added a `compiles_if_send_is_valid` test to prevent a regression like this from happening in the future.

I've released version `0.2.1` that has this issue fixed.

For future reference, it's the usual footgun of the scope of an unsendable value going through an await, even though its actual lifetime is shorter.

**Comment by adnanademovic** [comment]
Once you verify that the new version works for you, please close the issue.

**Comment by alexanderjanke** [comment]
Works like a charm now. Thanks a bunch
