### ISSUE TITLE
[Bug] Loading textures command always refreshes all cars

### ISSUE THREAD

**Issue by alexanderjanke** [adnanademovic/simetry#4]
Mode should be 1 when specifying a car_idx.
As of now right the `fn car()` still refreshes all cars in the session.

See reference: https://github.com/SIMRacingApps/SIMRacingAppsSIMPluginiRacing/blob/master/src/com/SIMRacingApps/SIMPlugins/iRacing/BroadcastMsg.java#L190

Should be fixed in this PR:
https://github.com/adnanademovic/simetry/pull/3

**Comment by adnanademovic** [comment]
Released the fix as `0.2.2`.

Thanks again and sorry for the long wait.
